services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: polyglot-postgres
    command: postgres -c shared_preload_libraries=timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: netops
      POSTGRES_DB: netops
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d netops"]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: polyglot-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5


volumes:
  pgdata:
  redisdata:
